const $=s=>document.querySelector(s), screens=[...document.querySelectorAll(".screen")];
const show=id=>screens.forEach(x=>x.classList.toggle("active",x.id===id));
let timerId=null,touchStartY=0;
const state={teams:["Kék csapat","Piros csapat"],players:[[],[]],scores:[0,0],cycles:2,duration:60,suddenDeath:true,gameChanger:true,sequence:[],pos:0,deck:[],card:null,time:60,paused:false,gameStarted:false,turnStats:{correct:0,pass:0,tabu:0},pendingDice:null};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function feedback(){if($("#vibrate")?.checked&&navigator.vibrate)navigator.vibrate(100)}
function addPlayer(t,name=""){const box=$("#team"+(t+1)+"Players"),row=document.createElement("div");row.className="player-row";const i=document.createElement("input");i.placeholder=`Játékos ${box.children.length+1}`;i.value=name;const b=document.createElement("button");b.type="button";b.className="remove-player";b.textContent="✕";b.onclick=()=>{if(box.children.length>1){row.remove()}};row.append(i,b);box.append(row)}
function getPlayers(t){return [...$("#team"+(t+1)+"Players").querySelectorAll("input")].map((x,i)=>x.value.trim()||`Játékos ${i+1}`)}
function buildSequence(){const a=state.players[0],b=state.players[1],max=Math.max(a.length,b.length);state.sequence=[];for(let c=1;c<=state.cycles;c++){for(let i=0;i<max;i++){if(a[i])state.sequence.push({team:0,player:i,cycle:c});if(b[i])state.sequence.push({team:1,player:i,cycle:c})}}}
function nextCard(){if(!state.deck.length)state.deck=shuffle(TABU_CARDS);state.card=state.deck.pop();$("#category").textContent=state.card.category||"";$("#difficultyLabel").textContent=state.card.difficulty||"";$("#word").textContent=state.card.word;$("#tabooList").innerHTML=state.card.taboo.map(x=>`<li>❌ ${x}</li>`).join("")}
function current(){return state.sequence[state.pos]}
function update(){const c=current();if(!c)return;$("#score1").textContent=state.scores[0];$("#score2").textContent=state.scores[1];$("#roundLabel").textContent=`${c.cycle}. forduló`;$("#teamLabel").textContent=state.teams[c.team];$("#playerLabel").textContent=`Magyaráz: ${state.players[c.team][c.player]}`;$("#timer").textContent=`${String(Math.floor(state.time/60)).padStart(2,"0")}:${String(state.time%60).padStart(2,"0")}`;$("#timer").classList.toggle("warning",state.time<=10);$("#progressBar").style.width=`${Math.max(0,state.time/state.duration*100)}%`}
function startTimer(){clearInterval(timerId);state.time=state.pendingDice==="double"?state.duration*2:state.duration;state.paused=false;update();timerId=setInterval(()=>{if(state.paused)return;if(--state.time<=0)endTurn();update()},1000)}
function startGame(){state.teams=[$("#team1").value.trim()||"Kék csapat",$("#team2").value.trim()||"Piros csapat"];state.players=[getPlayers(0),getPlayers(1)];state.cycles=+$("#cycles").value;state.duration=+$("#duration").value;state.suddenDeath=$("#suddenDeath").checked;state.gameChanger=$("#gameChanger").checked;state.scores=[0,0];state.pos=0;state.deck=shuffle(TABU_CARDS);state.gameStarted=true;state.turnStats={correct:0,pass:0,tabu:0};buildSequence();show("game");nextCard();if(state.gameChanger)showDiceBeforeTurn();else startTimer()}
function showDiceBeforeTurn(){const r=shuffle(["single","double","statue","all","classic"])[0];state.pendingDice=r;const d={single:["👤","EGY KITALÁLÓ!","Csak a kijelölt csapattárs tippelhet."],double:["⏱️","DUPLA IDŐ!","Ebben a körben dupla idő áll rendelkezésre."],statue:["🗿","SZOBOR!","A magyarázó nem gesztikulálhat és nem mozdulhat el."],all:["🌐","MINDENKI JÁTSZIK!","Mindkét csapat tippelhet."],classic:["🎯","KLASSZIKUS JÁTÉK","Nincs külön módosítás."]}[r];$("#diceIcon").textContent=d[0];$("#diceTitle").textContent=d[1];$("#diceDescription").textContent=d[2];$("#diceOverlay").classList.remove("hidden")}
$("#diceContinueBtn").onclick=()=>{$("#diceOverlay").classList.add("hidden");startTimer()}
function endTurn(){clearInterval(timerId);timerId=null;if(state.pos+1<state.sequence.length){showTurnEnd(false);return}if(state.scores[0]===state.scores[1]&&state.suddenDeath){buildSuddenDeath();showTurnEnd(true);return}endGame()}
function buildSuddenDeath(){const a=state.players[0],b=state.players[1],m=Math.max(a.length,b.length);state.sequence=[];for(let i=0;i<m;i++){if(a[i])state.sequence.push({team:0,player:i,cycle:"⚡"});if(b[i])state.sequence.push({team:1,player:i,cycle:"⚡"})}state.pos=0}
function showTurnEnd(sd){const c=current();$("#roundEndTitle").textContent=sd?"Döntetlen – hirtelen halál!":"Kör vége";$("#roundStats").textContent=sd?"Mindkét csapat ugyanannyi lehetőséget kap. Addig folytatjuk, amíg egy teljes páros után valaki vezet.":`${state.teams[c.team]} – ${state.players[c.team][c.player]}: +${state.turnStats.correct} megfejtés · ${state.turnStats.tabu} TABU · ${state.turnStats.pass} passz`;$("#nextRoundBtn").textContent=sd?"Hirtelen halál indítása →":"Következő játékos →";show("roundEnd")}
function continueAfterTurn(){state.turnStats={correct:0,pass:0,tabu:0};if(current()?.cycle==="⚡"&&state.pos%2===1&&state.scores[0]!==state.scores[1])return endGame();if(state.pos+1>=state.sequence.length)return endGame();state.pos++;show("game");nextCard();if(state.gameChanger)showDiceBeforeTurn();else startTimer()}
$("#correctBtn").onclick=()=>{const c=current();state.scores[c.team]++;state.turnStats.correct++;feedback();nextCard();update()};
$("#passBtn").onclick=()=>{const c=current();state.scores[1-c.team]++;state.turnStats.pass++;feedback();nextCard();update()};
$("#tabooBtn").onclick=()=>{const c=current();state.scores[1-c.team]++;state.turnStats.tabu++;feedback();nextCard();update()};
function pauseGame(){if(state.gameStarted&&timerId!==null){state.paused=true;$("#pauseOverlay").classList.remove("hidden")}}
function resumeGame(){state.paused=false;$("#pauseOverlay").classList.add("hidden");update()}
function goHome(){clearInterval(timerId);timerId=null;state.gameStarted=false;state.paused=false;$("#pauseOverlay").classList.add("hidden");$("#diceOverlay").classList.add("hidden");show("home")}
$("#pauseBtn").onclick=pauseGame;$("#gameMenuBtn").onclick=pauseGame;$("#resumeBtn").onclick=resumeGame;$("#pauseHomeBtn").onclick=goHome;$("#pauseEndBtn").onclick=goHome;
function endGame(){state.gameStarted=false;clearInterval(timerId);timerId=null;const[a,b]=state.scores;$("#winner").textContent=a===b?"Döntetlen!":`${a>b?state.teams[0]:state.teams[1]} nyert!`;$("#finalScores").innerHTML=`<div>🔵 ${state.teams[0]}: ${a}</div><div>🔴 ${state.teams[1]}: ${b}</div>`;show("gameEnd")}
$("#startBtn").onclick=startGame;$("#nextRoundBtn").onclick=continueAfterTurn;
$("#newGameBtn").onclick=()=>show("setup");$("#againBtn").onclick=()=>show("setup");$("#homeBtn").onclick=()=>show("home");$("#rulesBtn").onclick=()=>show("rules");$("#settingsBtn").onclick=()=>show("settings");
document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>show(b.dataset.back));
$("#addTeam1").onclick=()=>addPlayer(0);$("#addTeam2").onclick=()=>addPlayer(1);
addPlayer(0,"Játékos 1");addPlayer(0,"Játékos 2");addPlayer(1,"Játékos 1");addPlayer(1,"Játékos 2");
document.addEventListener("touchstart",e=>{if(e.touches.length===1)touchStartY=e.touches[0].clientY},{passive:true});
document.addEventListener("touchmove",e=>{if(e.touches.length===1&&window.scrollY===0&&e.touches[0].clientY-touchStartY>0)e.preventDefault()},{passive:false});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
